import Head from "next/head";
import { Fragment } from "react";

import {Button, CssBaseline, Typography} from "@mui/material";

export default function Home() {
  return (
    <Fragment>
      <Head>
        <title>Use Budget Tracker</title>
        <meta
          name="description"
          content="use a bugdet tracker generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CssBaseline />
      <Button color="test" variant="contained">
        Hello World
      </Button>
      <Typography variant="h1">Hello World</Typography>
    </Fragment>
  );
}
