import Head from "next/head";
import { Fragment } from "react";

import CssBaseline from "@mui/material/CssBaseline";
import Button from "@mui/material/Button";

export default function Home() {

  return (
    <Fragment>
      <Head>
        <title>Use Budget Tracker</title>
        <meta
          name="description"
          content="use a bugdet tracker generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CssBaseline />
      <main>
        <Button variant="contained">Hello World</Button>
      </main>
    </Fragment>
  );
}
